packages:
- logtape
- file
- otel
- redaction
- docs

catalog:
  "@david/which-runtime": "jsr:^0.2.1"
  "@hongminhee/suite": ^0.6.2
  "@std/assert": "jsr:^1.0.13"
  "@std/async": "jsr:^1.0.13"
  "@std/path": "jsr:^1.1.0"
  consolemock: ^1.1.0
  tsdown: ^0.12.7
  typescript: ^5.8.3
